# Generated by Django 3.0.5 on 2020-04-29 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='produts',
            new_name='products',
        ),
    ]
